//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOWS_Training_Room.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalText_zh_Hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalText_zh_Hans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WOWS_Training_Room.Resources.GlobalText.zh_Hans", typeof(GlobalText_zh_Hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the game first before watching your last battle..
        /// </summary>
        public static string CLOSE_GAME {
            get {
                return ResourceManager.GetString("CLOSE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Replay Mode.
        /// </summary>
        public static string CLOSE_REPLAY {
            get {
                return ResourceManager.GetString("CLOSE_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Training Room.
        /// </summary>
        public static string CLOSE_TRAINING {
            get {
                return ResourceManager.GetString("CLOSE_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to use this function?.
        /// </summary>
        public static string DOUBLE_CHECK {
            get {
                return ResourceManager.GetString("DOUBLE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable replay mode first..
        /// </summary>
        public static string ENABLE_REPLAY_FIRST {
            get {
                return ResourceManager.GetString("ENABLE_REPLAY_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy playing World of Warships!.
        /// </summary>
        public static string ENJOY_GAME {
            get {
                return ResourceManager.GetString("ENJOY_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If more features are needed, please download and install modpack online. This program is only an alternative way to enable some hidden features..
        /// </summary>
        public static string MORE_FUNCTIONS {
            get {
                return ResourceManager.GetString("MORE_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no backup file..
        /// </summary>
        public static string NO_BACKUP {
            get {
                return ResourceManager.GetString("NO_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not edit data.txt.
        /// </summary>
        public static string NO_HACKING {
            get {
                return ResourceManager.GetString("NO_HACKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no MOD to remove..
        /// </summary>
        public static string NO_MOD {
            get {
                return ResourceManager.GetString("NO_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Replay Mode.
        /// </summary>
        public static string OPEN_REPLAY {
            get {
                return ResourceManager.GetString("OPEN_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Training Room.
        /// </summary>
        public static string OPEN_TRIANING {
            get {
                return ResourceManager.GetString("OPEN_TRIANING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste your game path into the textbox below..
        /// </summary>
        public static string PASTE_PATH {
            get {
                return ResourceManager.GetString("PASTE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste a valid game path below..
        /// </summary>
        public static string PASTE_VALID_PATH {
            get {
                return ResourceManager.GetString("PASTE_VALID_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This path is not correct..
        /// </summary>
        public static string PATH_NOT_CORRECT {
            get {
                return ResourceManager.GetString("PATH_NOT_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove all MODs?.
        /// </summary>
        public static string REMOVE_MODS {
            get {
                return ResourceManager.GetString("REMOVE_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please only use this if you found your game having strange behaviour..
        /// </summary>
        public static string STRANGE_BEHAVIOUR {
            get {
                return ResourceManager.GetString("STRANGE_BEHAVIOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using this program ^_^.
        /// </summary>
        public static string THX_FOR_USING {
            get {
                return ResourceManager.GetString("THX_FOR_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling this program.
        /// </summary>
        public static string UNINSTALL_THIS_PROGRAM {
            get {
                return ResourceManager.GetString("UNINSTALL_THIS_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to uninstall this program?.
        /// </summary>
        public static string UNINSTALL_THIS_PROGRAM_TEXT {
            get {
                return ResourceManager.GetString("UNINSTALL_THIS_PROGRAM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome &gt;_&lt;.
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst Server Ever!.
        /// </summary>
        public static string WORSE_SERVER {
            get {
                return ResourceManager.GetString("WORSE_SERVER", resourceCulture);
            }
        }
    }
}
