//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOWS_Training_Room.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WOWS_Training_Room.Resources.GlobalText", typeof(GlobalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭游戏之后才可以看上次的战斗哦&gt;_&lt;.
        /// </summary>
        public static string CLOSE_GAME {
            get {
                return ResourceManager.GetString("CLOSE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭回放功能.
        /// </summary>
        public static string CLOSE_REPLAY {
            get {
                return ResourceManager.GetString("CLOSE_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭训练房.
        /// </summary>
        public static string CLOSE_TRAINING {
            get {
                return ResourceManager.GetString("CLOSE_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真的要使用这项功能么？.
        /// </summary>
        public static string DOUBLE_CHECK {
            get {
                return ResourceManager.GetString("DOUBLE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先打开回放功能。.
        /// </summary>
        public static string ENABLE_REPLAY_FIRST {
            get {
                return ResourceManager.GetString("ENABLE_REPLAY_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 享受每一次战斗吧！.
        /// </summary>
        public static string ENJOY_GAME {
            get {
                return ResourceManager.GetString("ENJOY_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这只是一个辅助用的小程序。它可以启动回放功能，开启一次性的训练房和其他的一些小功能。如果需要更多的功能，请下载ASLAIN的MOD。.
        /// </summary>
        public static string MORE_FUNCTIONS {
            get {
                return ResourceManager.GetString("MORE_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没有备份文件哦.
        /// </summary>
        public static string NO_BACKUP {
            get {
                return ResourceManager.GetString("NO_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请不要修改数据文件.
        /// </summary>
        public static string NO_HACKING {
            get {
                return ResourceManager.GetString("NO_HACKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有要删除的MOD。.
        /// </summary>
        public static string NO_MOD {
            get {
                return ResourceManager.GetString("NO_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动回放功能.
        /// </summary>
        public static string OPEN_REPLAY {
            get {
                return ResourceManager.GetString("OPEN_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启训练房.
        /// </summary>
        public static string OPEN_TRIANING {
            get {
                return ResourceManager.GetString("OPEN_TRIANING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请将游戏路径复制到下面的文本框中。.
        /// </summary>
        public static string PASTE_PATH {
            get {
                return ResourceManager.GetString("PASTE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请复制一个有效的路径。.
        /// </summary>
        public static string PASTE_VALID_PATH {
            get {
                return ResourceManager.GetString("PASTE_VALID_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个路径不正确。。。 姆姆姆&gt;_&lt; .
        /// </summary>
        public static string PATH_NOT_CORRECT {
            get {
                return ResourceManager.GetString("PATH_NOT_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真的要删除所有安装的MOD么？.
        /// </summary>
        public static string REMOVE_MODS {
            get {
                return ResourceManager.GetString("REMOVE_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果无法正常进行游戏，请尝试这项功能。.
        /// </summary>
        public static string STRANGE_BEHAVIOUR {
            get {
                return ResourceManager.GetString("STRANGE_BEHAVIOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感谢你使用这个小程序 &gt;_&lt;.
        /// </summary>
        public static string THX_FOR_USING {
            get {
                return ResourceManager.GetString("THX_FOR_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除游戏.
        /// </summary>
        public static string UNINSTALL_THIS_PROGRAM {
            get {
                return ResourceManager.GetString("UNINSTALL_THIS_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真的要删除这个游戏么 &gt;_&lt;.
        /// </summary>
        public static string UNINSTALL_THIS_PROGRAM_TEXT {
            get {
                return ResourceManager.GetString("UNINSTALL_THIS_PROGRAM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告！.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎哦 &gt;_&lt;.
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最差的服务器！.
        /// </summary>
        public static string WORSE_SERVER {
            get {
                return ResourceManager.GetString("WORSE_SERVER", resourceCulture);
            }
        }
    }
}
